import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/PageComponent/Navbar/Header";
import Footer from "@/PageComponent/Footer/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header  />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
